import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./ui/context/auth";

export const metadata: Metadata = {
  title: "Realty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
